routes/web.php
<?php
Route::group(['namespace' => 'Blog'], function() {
    Route::name('home')->get('/', 'HomeController@index');
    Route::name('front.page')->get('/pages/{page}', 'ShowPage');
    Route::name('front.specialties.search')->get('/specialties/search', 'SpecialtiesSearch');

    Route::name('front.article.index')->get('/article', 'ArticleController@index');
    Route::name('front.article.category')->get('/article/category/{category}', 'ShowArticleCategory');
    Route::name('front.article.detail')->get('/article/{article}', 'ArticleController@detail');

    Route::name('front.event.index')->get('/events', 'EventController@index');
    Route::name('front.event.detail')->get('/events/{event}', 'EventController@detail');
    Route::name('front.event.search')->get('/events/search', 'EventController@search');

    Route::name('front.product.index')->get('/product', 'ProductController@index');
    Route::name('front.product.category')->get('/product/category/{category}', 'ProductController@category');
    Route::name('front.product.detail')->get('/product/{category}/{product}', 'ProductController@detail');
    Route::name('front.product.search')->get('/product/search', 'ProductController@search');

    Route::name('front.specialty.index')->get('/specialty', 'SpecialtyController@index');
    Route::name('front.specialty.category')->get('/specialty/{category}', 'SpecialtyController@category');
    Route::name('front.specialty.detail')->get('/specialty/{category}/{specialty}', 'SpecialtyController@detail');

    Route::name('front.blog.index')->get('/blog', 'ArticleController@index');

    Route::name('front.contact-us')->get('contact-us', 'ContactController@index');
    Route::name('front.partnership')->get('partnership', 'PartnershipController@index');
    Route::name('front.contact')->post('/home/contact', 'ContactController@sendMail');
});

Route::group(['prefix' => 'admin'], function () {
  Auth::routes();

  Route::group(['middleware' => 'auth','namespace' => 'Admin'], function() {
    Route::name('admin')->get('/', 'HomeController@index');
    Route::resource('/article', 'ArticleController', ['names' => 'admin.article']);

    Route::name('admin.category.index')->get('/category', 'CategoryController@index');
    Route::name('admin.category.create')->get('/category/create', 'CategoryController@create');
    Route::name('admin.category.show')->get('/category/{id}/show', 'CategoryController@show');
    Route::name('admin.category.edit')->get('/category/edit/{id}', 'CategoryController@edit');
    Route::name('admin.category.destroy')->delete('/category/{id}', 'CategoryController@destroy');
    Route::name('admin.category.store')->post('/category', 'CategoryController@store');
    Route::name('admin.category.update')->put('/category/{id}', 'CategoryController@update');

    Route::resource('/contact', 'ContactController', ['names' => 'admin.contact']);
    Route::resource('/event', 'EventController', ['names' => 'admin.event']);
    Route::resource('/menu', 'MenuController', ['names' => 'admin.menu']);
    Route::resource('/page', 'PageController', ['names' => 'admin.page']);
    Route::name('admin.product.index')->get('/product', 'ProductController@index');
    Route::name('admin.product.create')->get('/product/create', 'ProductController@create');
    Route::name('admin.product.show')->get('/product/{id}/show', 'ProductController@show');
    Route::name('admin.product.edit')->get('/product/edit/{id}', 'ProductController@edit');
    Route::name('admin.product.destroy')->delete('/product/{id}', 'ProductController@destroy');
    Route::name('admin.product.store')->post('/product', 'ProductController@store');
    Route::name('admin.product.update')->put('/product/{id}', 'ProductController@update');

    Route::resource('/setting', 'SettingController', ['names' => 'admin.setting']);
    Route::resource('/social', 'SocialController', ['names' => 'admin.social']);
    Route::resource('/specialty', 'SpecialtyController', ['names' => 'admin.specialty']);
    Route::resource('/tag', 'TagController', ['names' => 'admin.tag']);
    Route::resource('/user', 'UserController', ['names' => 'admin.user']);

    Route::name('admin.password.edit')->get('/profil/password/{user}/edit', 'UserProfileController@editPassword');
    Route::name('admin.password.update')->put('/profil/password/{user}', 'UserProfileController@updatePassword');
    Route::name('admin.profil.index')->get('/profil', 'UserProfileController@index');
    Route::name('admin.profil.create')->get('/profil/create', 'UserProfileController@create');
    Route::name('admin.profil.store')->post('/profil/store', 'UserProfileController@store');
    Route::name('admin.profil.update')->put('/profil/update/{user}', 'UserProfileController@update');
    Route::name('admin.profil.edit')->get('/profil/edit/{user}', 'UserProfileController@edit');

    Route::name('admin.user.edit')->get('/user/edit/{user}', 'UserController@edit');
    Route::name('admin.user.update')->put('/user/update/{user}', 'UserController@update');
  });

});

resources/views/admin/page/create.blade.php
@extends('layouts.admin.template')
@section('title', 'Tambah Halaman')

@section('breadcrumb')
<div id="breadcrumb">
	<ul class="breadcrumb">
		 <li><i class="fa fa-home"></i><a onclick="location.href='{{ route('admin') }}'"> Home</a></li>
		 <li></i><a onclick="location.href='{{ route('admin.page.index') }}'">Halaman</a></li>
		 <li class="active">Tambah</li>
	</ul>
</div>
@endsection

@section('content')
<div class="panel panel-primary">
	<div class="panel-heading">@yield('title')</div>
	<div class="panel-body">
		{!! Form::open(array('route' => 'admin.page.store', 'methode' => 'POST', 'class' => 'form-horizontal', 'enctype' => 'multipart/form-data')) !!}

		<div class="form-group">
			<label for="title" class="col-sm-2 control-label">Judul Halaman</label>
			<div class="col-sm-10">
				<input type="text" name="title" class="form-control" id="title" placeholder="Judul Halaman" value="">
			</div>
		</div>

		<div class="form-group">
			<label for="content" class="col-sm-2 control-label">Konten Halaman</label>
			<div class="col-sm-10">
				<textarea id="content" name="content" placeholder="Masukan konten halaman disini..." class="form-control" rows="6"></textarea>
			</div>
		</div>
		<div class="form-group">
			<label for="picture" class="col-sm-2 control-label">Gambar</label>
			<div class="col-sm-5">
				<div class="upload-file">
					<input type="file" name="picture" id="picture" class="picture">
					<label data-title="Pilih gambar" for="picture">
						<span data-title="Tidak ada gambar dipilih"></span>
					</label>
				</div>
				<br>
			</div>
		</div>
		<div class="form-group">
			<label for="active" class="col-sm-2 control-label">Publish</label>
			<div class="col-lg-10">
				<label class="label-radio inline">
					<input type="radio" name="active" value="Y">
					<span class="custom-radio"></span>
					Active
				</label>
				<label class="label-radio inline">
					<input type="radio" name="active" value="N">
					<span class="custom-radio"></span>
					Non Active
				</label>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
				<a onclick="location.href='{{ route('admin.page.index') }}'" class="btn btn-danger"><i class="fa fa-arrow-left"></i> Kembali</a>
			</div>
		</div>
		{!! Form::close() !!}
	</div>
</div>
@endsection

@section('style')
<link href="{{ asset('ckeditor/content.css') }}" rel="stylesheet"/>
<link href="{{ asset('asset_admin/css/gritter/jquery.gritter.css') }}" rel="stylesheet">
@endsection

@section('js')
<script src="{{ asset('ckeditor/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('asset_admin/js/jquery.gritter.min.js') }}"></script>
<script>
	CKEDITOR.replace( 'content');

	$('.picture').change(function()	{
		var filename = $(this).val().split('\\').pop();
		$(this).parent().find('span').attr('data-title',filename);
		$(this).parent().find('label').attr('data-title','Change file');
		$(this).parent().find('label').addClass('selected');
	});
</script>

@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <script>
			$.gritter.add({
				title: '<i class="fa fa-warning"></i> Error',
				text: '{{ $error }}',
				sticky: false,
				time: '5000',
				class_name: 'gritter-danger'
			});
        </script>
    @endforeach
@endif

@endsection

resources/views/admin/page/edit.blade.php
@extends('layouts.admin.template')
@section('title', 'Edit Halaman')
@section('content')

<section class="panel panel-primary">
	<header class="panel-heading">Edit Halaman</header>
	<div class="panel-body">

	{!! Form::open(['route' => ['admin.page.update', $page], 'method' => 'PUT', 'class' => 'form-horizontal', 'enctype' => 'multipart/form-data']) !!}

		<div class="form-group">
			<label for="title" class="col-sm-2 control-label">Judul Halaman</label>
			<div class="col-sm-10">
				<input type="text" name="title" class="form-control" id="title" placeholder="Judul Halaman" value="{{ $page->title }}">
			</div>
		</div>

		<div class="form-group">
			<label for="content" class="col-sm-2 control-label">Konten Halaman</label>
			<div class="col-sm-10">
				<textarea id="content" name="content" placeholder="Masukan konten halaman anda disini..." class="form-control" rows="6">
					{{ $page->content }}
				</textarea>
			</div>
		</div>
		<div class="form-group">
			<label for="picture" class="col-sm-2 control-label">Gambar</label>
			<div class="col-sm-5">
				<div class="upload-file">
					<input type="file" name="picture" id="picture" class="picture">
					<label data-title="Pilih gambar" for="picture">
						<span data-title="Tidak ada gambar dipilih"></span>
					</label>
				</div>
				<br>
			</div>
		</div>
		<div class="form-group">
			<label for="active" class="col-sm-2 control-label">Publish</label>
			<div class="col-lg-10">
				@if ($page->active == 'Y')
					<label class="label-radio inline">
						<input type="radio" name="active" value="Y" checked>
						<span class="custom-radio"></span>
						Aktif
					</label>
					<label class="label-radio inline">
						<input type="radio" name="active" value="N">
						<span class="custom-radio"></span>
						Non Aktif
					</label>
		        @else
					<label class="label-radio inline">
						<input type="radio" name="active" value="Y">
						<span class="custom-radio"></span>
						Aktif
					</label>
					<label class="label-radio inline">
						<input type="radio" name="active" value="N" checked>
						<span class="custom-radio"></span>
						Non Aktif
					</label>
		        @endif

			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
				<a onclick="location.href='{{ route('admin.page.index') }}'" class="btn btn-danger"><i class="fa fa-arrow-left"></i> Kembali</a>
			</div>
		</div>
		{!! Form::close() !!}
	</div>
</section>
@endsection


@section('style')
<link href="{{ asset('ckeditor/content.css') }}" rel="stylesheet"/>
<link href="{{ asset('asset_admin/css/gritter/jquery.gritter.css') }}" rel="stylesheet">
@endsection

@section('js')
<script src="{{ asset('ckeditor/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('asset_admin/js/jquery.gritter.min.js') }}"></script>
<script>
CKEDITOR.replace( 'content' );
</script>
@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <script>
			$.gritter.add({
				title: '<i class="fa fa-warning"></i> Error',
				text: '{{ $error }}',
				sticky: false,
				time: '5000',
				class_name: 'gritter-danger'
			});
        </script>
    @endforeach
@endif
@endsection

resources/views/admin/page/index.blade.php
@extends('layouts.admin.template')
@section('title', 'Halaman')
@section('breadcrumb')
<div id="breadcrumb">
	<ul class="breadcrumb">
		 <li><i class="fa fa-home"></i><a onclick="location.href='{{ route('admin') }}'"> Home</a></li>
		 <li class="active">@yield('title')</li>
	</ul>
</div>
@endsection
@section('content')
<div class="panel panel-primary table-responsive">
	<div class="panel-heading">&nbsp;</div>
	<div class="padding-md clearfix">
		@section('button')
		<a onclick="location.href='{{ route('admin.page.create') }}'" class="btn btn-primary btn-small"><i class="fa fa-plus"></i> Tambah @yield('title') </a>
		@endsection
		{!! $html->table(['class' => 'table table-striped']) !!}
	</div>
</div>
<div class="modal fade modal-detail" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
  <div class="modal-dialog modal-lg" style="overflow-y: scroll; max-height:85%; margin-top: 50px; margin-bottom:50px;" >
    <div class="modal-content">
      <div class="modal-body">
        <div id="modalcontent"></div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('style')
<link href="{{ asset('asset_admin/css/jquery.dataTables_themeroller.css') }}" rel="stylesheet">
<link href="{{ asset('asset_admin/css/sweetalert.css') }}" rel="stylesheet">
@endsection

@section('js')
<script src="{{ asset('asset_admin/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('asset_admin/js/clipboard.js') }}"></script>
<script src="{{ asset('asset_admin/js/sweetalert.min.js') }}"></script>
<script type="text/javascript">
	 function show(target){
		 var target = target.getAttribute('data-href');
		 $('#modalcontent').load(target);
	 }

	 function konfirm(href){
			 var href = href.getAttribute('data-href');
			 swal({
					 title: "Are you sure?",
					 text: "You will not be able to recover this data file!",
					 type: "warning",
					 showCancelButton: true,
					 confirmButtonColor: "#DD6B55",
					 confirmButtonText: "Yes, delete it!",
					 closeOnConfirm: false,
					 showLoaderOnConfirm: true
			 },
			 function(){
					 $.ajax({
							 type: "POST",
							 url: href,
							 data: {
									 '_token': "{{ csrf_token() }}",
									 '_method' : 'DELETE'
							 },
							 success: function() {
									 $('#dataTableBuilder').DataTable().ajax.reload();
									 swal("Deleted!", "Help Berhasil Dihapus!", "success");
							 },
							 error: function() {
									 swal("Error!", "Help Gagal Dihapus!", "error");
							 }
					 });
			 });
	 }
</script>
{!! $html->scripts() !!}
@endsection

resources/views/admin/page/show.blade.php
<div class="panel blog-container">
	<div class="panel-body">
		<h4>{{ $page->title }}</h4>
		<small class="text-muted">Tanggal : {{ tglIndo($page->created_at) }} </small>
		<div class="seperator"></div>
    <div class="input-group">
				<input id="slug" type="text" value="{{ 'pages/'.$page->slug }}" class="form-control">
				<span class="input-group-btn">
					<button class="btn btn-success copy-button" data-clipboard-action="copy" data-clipboard-target="#slug">Copy</button>
				</span>
			</div>
		<div class="seperator"></div>
		@if( $page->picture != '' )
		<img width="200px" class="img-thumbnail" style="float:left; margin-right:10px" src="{{ url('storage/uploads/page/'.$page->picture) }}" alt="{{ $page->title }}">
		@endif
		{!! $page->content !!}

	</div>
</div>