routes/web.php
<?php
Route::group(['namespace' => 'Blog'], function() {
    Route::name('home')->get('/', 'HomeController@index');
    Route::name('front.page')->get('/pages/{page}', 'ShowPage');
    Route::name('front.specialties.search')->get('/specialties/search', 'SpecialtiesSearch');

    Route::name('front.article.index')->get('/article', 'ArticleController@index');
    Route::name('front.article.category')->get('/article/category/{category}', 'ShowArticleCategory');
    Route::name('front.article.detail')->get('/article/{article}', 'ArticleController@detail');

    Route::name('front.event.index')->get('/events', 'EventController@index');
    Route::name('front.event.detail')->get('/events/{event}', 'EventController@detail');
    Route::name('front.event.search')->get('/events/search', 'EventController@search');

    Route::name('front.product.index')->get('/product', 'ProductController@index');
    Route::name('front.product.category')->get('/product/category/{category}', 'ProductController@category');
    Route::name('front.product.detail')->get('/product/{category}/{product}', 'ProductController@detail');
    Route::name('front.product.search')->get('/product/search', 'ProductController@search');

    Route::name('front.specialty.index')->get('/specialty', 'SpecialtyController@index');
    Route::name('front.specialty.category')->get('/specialty/{category}', 'SpecialtyController@category');
    Route::name('front.specialty.detail')->get('/specialty/{category}/{specialty}', 'SpecialtyController@detail');

    Route::name('front.blog.index')->get('/blog', 'ArticleController@index');

    Route::name('front.contact-us')->get('contact-us', 'ContactController@index');
    Route::name('front.partnership')->get('partnership', 'PartnershipController@index');
    Route::name('front.contact')->post('/home/contact', 'ContactController@sendMail');
});

Route::group(['prefix' => 'admin'], function () {
  Auth::routes();

  Route::group(['middleware' => 'auth','namespace' => 'Admin'], function() {
    Route::name('admin')->get('/', 'HomeController@index');
    Route::resource('/article', 'ArticleController', ['names' => 'admin.article']);

    Route::name('admin.category.index')->get('/category', 'CategoryController@index');
    Route::name('admin.category.create')->get('/category/create', 'CategoryController@create');
    Route::name('admin.category.show')->get('/category/{id}/show', 'CategoryController@show');
    Route::name('admin.category.edit')->get('/category/edit/{id}', 'CategoryController@edit');
    Route::name('admin.category.destroy')->delete('/category/{id}', 'CategoryController@destroy');
    Route::name('admin.category.store')->post('/category', 'CategoryController@store');
    Route::name('admin.category.update')->put('/category/{id}', 'CategoryController@update');

    Route::resource('/contact', 'ContactController', ['names' => 'admin.contact']);
    Route::resource('/event', 'EventController', ['names' => 'admin.event']);
    Route::resource('/menu', 'MenuController', ['names' => 'admin.menu']);
    Route::resource('/page', 'PageController', ['names' => 'admin.page']);
    Route::name('admin.product.index')->get('/product', 'ProductController@index');
    Route::name('admin.product.create')->get('/product/create', 'ProductController@create');
    Route::name('admin.product.show')->get('/product/{id}/show', 'ProductController@show');
    Route::name('admin.product.edit')->get('/product/edit/{id}', 'ProductController@edit');
    Route::name('admin.product.destroy')->delete('/product/{id}', 'ProductController@destroy');
    Route::name('admin.product.store')->post('/product', 'ProductController@store');
    Route::name('admin.product.update')->put('/product/{id}', 'ProductController@update');

    Route::resource('/setting', 'SettingController', ['names' => 'admin.setting']);
    Route::resource('/social', 'SocialController', ['names' => 'admin.social']);
    Route::resource('/specialty', 'SpecialtyController', ['names' => 'admin.specialty']);
    Route::resource('/tag', 'TagController', ['names' => 'admin.tag']);
    Route::resource('/user', 'UserController', ['names' => 'admin.user']);

    Route::name('admin.password.edit')->get('/profil/password/{user}/edit', 'UserProfileController@editPassword');
    Route::name('admin.password.update')->put('/profil/password/{user}', 'UserProfileController@updatePassword');
    Route::name('admin.profil.index')->get('/profil', 'UserProfileController@index');
    Route::name('admin.profil.create')->get('/profil/create', 'UserProfileController@create');
    Route::name('admin.profil.store')->post('/profil/store', 'UserProfileController@store');
    Route::name('admin.profil.update')->put('/profil/update/{user}', 'UserProfileController@update');
    Route::name('admin.profil.edit')->get('/profil/edit/{user}', 'UserProfileController@edit');

    Route::name('admin.user.edit')->get('/user/edit/{user}', 'UserController@edit');
    Route::name('admin.user.update')->put('/user/update/{user}', 'UserController@update');
  });

});

resources/views/layouts/admin/partial/_footer.blade.php
<footer>
  <div class="row">
    <div class="col-sm-6">
      <span class="footer-brand">
        <strong class="text-danger">{{ config('app.name') }}</strong> Admin
      </span>
      <p class="no-margin">
        &copy; <?php echo date('Y'); ?> <strong>{{ config('app.name') }}</strong>. ALL Rights Reserved.
      </p>
    </div>
  </div>
</footer>


<a href="#" id="scroll-to-top" class="hidden-print"><i class="fa fa-chevron-up"></i></a>
<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
  {{ csrf_field() }}
</form>

<div class="custom-popup width-100" id="logoutConfirm">
<div class="padding-md">
  <h4 class="m-top-none"> Apakah anda ingin keluar dari halaman administrator?</h4>
</div>
<div class="text-center">
  <a class="btn btn-success m-right-sm" href="{{ route('logout') }}" onclick="event.preventDefault();
    document.getElementById('logout-form').submit();">Logout</a>
  <a class="btn btn-danger logoutConfirm_close">Cancel</a>
</div>
</div>
@include('layouts.admin.partial._script')

resources/views/layouts/admin/partial/_head.blade.php
<head>
  <meta charset="utf-8">
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>@yield('title') | Administrator {{ config('app.name') }}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Administrator {{ config('app.name') }}">
  <link rel="icon" type="image/gif" href="{{ asset('images/favicon.gif') }}">
  <link href="{{ asset('asset_admin/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ asset('asset_admin/css/font-awesome.min.css') }}" rel="stylesheet">
  <link href="{{ asset('asset_admin/css/chosen/chosen.min.css') }}" rel="stylesheet">
  <link href="{{ asset('asset_admin/css/pace.css') }}" rel="stylesheet">
  <link href="{{ asset('asset_admin/css/morris.css') }}" rel="stylesheet"/>
  <link href="{{ asset('asset_admin/css/app.min.css') }}" rel="stylesheet">
  <link href="{{ asset('asset_admin/css/app-skin.css') }}" rel="stylesheet">
  @yield('style')

</head>

resources/views/layouts/admin/partial/_menu.blade.php
<div class="main-menu">
  <ul>
    <?php
      $menu_0 = \App\Models\Menu::where('id_parent',0)->where('active', 'Y')->where('admin', 'Y')->get();
      foreach ($menu_0 as $key) {
        get_menu_child($key->id);
      }

      function get_menu_child($parent=0){
        $menu = \App\Models\Menu::where('id_parent',$parent)->get();
        $parent = \App\Models\Menu::where('id',$parent)->first();
        if(sizeof($menu) > 0){
        ?>
        <li class="openable">
          <a href="{{ url($parent->url) }}">
            <span class="menu-icon"><i class="fa {{ $parent->icon }} fa-lg"></i></span>
            <span class="text">{{ $parent->name }}  </span>
            <span class="badge badge-success bounceIn">{{ sizeof($menu) }}</span>
            <span class="menu-hover"></span>
          </a>
          <ul class="submenu">
            <?php foreach($menu as $key) { ?>
              <li><a href="{{ url($key->url) }}"><span class="submenu-label">{{ $key->name }}</span></a></li>
            <?php } ?>
          </ul>
        </li>
        <?php }else{ ?>
        <li class="{{ Request::is(url($parent->url)) ? 'active' : '' }}">
          <a href="{{ url($parent->url) }}">
            <span class="menu-icon"><i class="fa {{ $parent->icon }} fa-lg"></i></span>
            <span class="text">{{ $parent->name }}</span>
            <span class="menu-hover"></span>
          </a>
        </li>
        <?php } ?>
      <?php } ?>
      <li class="">
        <a href="{{ route('admin.menu.index') }}">
          <span class="menu-icon"><i class="fa fa-bars fa-lg"></i></span>
          <span class="text">Menu</span>
          <span class="menu-hover"></span>
        </a>
      </li>
  </ul>

</div>

resources/views/layouts/admin/partial/_script.blade.php
<script src="{{ asset('asset_admin/js/jquery-2.1.4.min.js') }}"></script>
<script src="{{ asset('asset_admin/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('asset_admin/js/jquery.sparkline.min.js') }}"></script>
<script src="{{ asset('asset_admin/js/pace.min.js') }}"></script>
<script src="{{ asset('asset_admin/js/jquery.popupoverlay.min.js') }}"></script>
<script src="{{ asset('asset_admin/js/jquery.slimscroll.min.js') }}"></script>
<script src="{{ asset('asset_admin/js/modernizr.min.js') }}"></script>
<script src="{{ asset('asset_admin/js/chosen.jquery.min.js') }}"></script>
<script src="{{ asset('asset_admin/js/jquery.cook.min.js') }}"></script>
<script src="{{ asset('asset_admin/js/app/app_dashboard.js') }}"></script>
<script src="{{ asset('asset_admin/js/app/app.js') }}"></script>

resources/views/layouts/admin/partial/_topNav.blade.php
<div id="top-nav" class="fixed default">
	<a href="{{ route('admin') }}" class="brand">
		<span>{{ config('app.name') }}</span>
		<span class="text-toggle">&nbsp;</span>
	</a>
	<button type="button" class="navbar-toggle pull-left" id="sidebarToggle">
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	</button>
	<button type="button" class="navbar-toggle pull-left hide-menu" id="menuToggle">
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	</button>
</div>